[package]
name = "tanuki"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "^0.30.5"
fxhash = "0.2.1"
boomphf = "0.6.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "palette"
harness = false

[[bench]]
name = "world"
harness = false
